CREATE TABLE hall
(row INT PRIMARY KEY,
 place_1 BOOLEAN,
 place_2 BOOLEAN,
 place_3 BOOLEAN);

CREATE TABLE accounts
(id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
phone TEXT NOT NULL,
hall INT,
place INT);
